### PR TITLE
Fixes Linking for OSX

### PR DESCRIPTION
**Pull request by labeneator**
OSX doesn't require the -lrt flag. This commit allows osx builds
to just work.
Fixes https://github.com/steve-m/kalibrate-rtl/issues/10

### CODE REVIEW

**Comment by labeneator** [comment]
Out of band coments (Please enable issue reporting). Would like a release tag for commit: 1a650b4. I am adding a homebrew recipe for this @ https://github.com/Homebrew/homebrew/pull/49791

**Comment by labeneator** [comment]
Please PR your changes upstream (https://github.com/steve-m/kalibrate-rtl)

**Comment by viraptor** [comment]
This is not the official repo - the issues are disabled on purpose. I'm just trying to collect existing fixes and happy to merge new ones, but I'm not going to do actual project maintenance.

**Pull request merged**
